# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui_0.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.unk_cat2 = QtWidgets.QPushButton(self.centralwidget)
        self.unk_cat2.setGeometry(QtCore.QRect(10, 200, 191, 41))
        self.unk_cat2.setText("")
        self.unk_cat2.setObjectName("unk_cat2")
        self.unk_cat1 = QtWidgets.QPushButton(self.centralwidget)
        self.unk_cat1.setGeometry(QtCore.QRect(10, 160, 191, 41))
        self.unk_cat1.setText("")
        self.unk_cat1.setObjectName("unk_cat1")
        self.cat_web = QtWidgets.QPushButton(self.centralwidget)
        self.cat_web.setGeometry(QtCore.QRect(10, 40, 191, 41))
        self.cat_web.setObjectName("cat_web")
        self.cat_pk = QtWidgets.QPushButton(self.centralwidget)
        self.cat_pk.setGeometry(QtCore.QRect(10, 80, 191, 41))
        self.cat_pk.setObjectName("cat_pk")
        self.create_key = QtWidgets.QPushButton(self.centralwidget)
        self.create_key.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.create_key.setObjectName("create_key")
        self.load_key = QtWidgets.QPushButton(self.centralwidget)
        self.load_key.setGeometry(QtCore.QRect(100, 10, 101, 23))
        self.load_key.setObjectName("load_key")
        self.cat_games = QtWidgets.QPushButton(self.centralwidget)
        self.cat_games.setGeometry(QtCore.QRect(10, 120, 191, 41))
        self.cat_games.setObjectName("cat_games")
        self.unk_menu = QtWidgets.QPushButton(self.centralwidget)
        self.unk_menu.setGeometry(QtCore.QRect(320, 10, 131, 23))
        self.unk_menu.setText("")
        self.unk_menu.setObjectName("unk_menu")
        self.add_category = QtWidgets.QPushButton(self.centralwidget)
        self.add_category.setGeometry(QtCore.QRect(200, 10, 121, 23))
        self.add_category.setObjectName("add_category")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(210, 40, 381, 201))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 260, 581, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cat_web.setText(_translate("MainWindow", "Веб-сайты"))
        self.cat_pk.setText(_translate("MainWindow", "ПК"))
        self.create_key.setText(_translate("MainWindow", "Создать ключ"))
        self.load_key.setText(_translate("MainWindow", "Загрузить ключ"))
        self.cat_games.setText(_translate("MainWindow", "Игры"))
        self.add_category.setText(_translate("MainWindow", "Добавить категорию"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
